By default subtitles are off
fluttercommunity/chewie pull request #700
Opened 2023-01-23 05:16 UTC by PranavMasekar

#648 
Added a parameter showSubtitle by default value is false.

2023-04-11 15:23 UTC, PranavMasekar commented
Anyone can have the folllow up ont this ??

2023-05-12 06:16 UTC, diegotori commented
@PranavMasekar Looks good to me. I'll release it this weekend.

2023-05-12 06:18 UTC, PranavMasekar commented
Sure thanks for the reply @diegotori 🤩🤩

2023-05-21 14:35 UTC, PranavMasekar commented
@diegotori Any updates on merging this PR ??

2023-05-21 14:35 UTC, PranavMasekar commented
@diegotori Any updates on merging this PR ??

2023-07-02 21:54 UTC, diegotori requested changes
Please re-sync your changes with `master`'s current changes.

Then work on the issues that were called out in your PR.

Thanks in advance.

2023-07-02 21:54 UTC, diegotori commented on lib/src/chewie_player.dart
> +  bool showSubtitle;
Make this `final`.

2023-07-02 21:54 UTC, diegotori commented on lib/src/chewie_player.dart
> +  /// Option to disable subtitle by default
Replace the documentation with:

```dart
/// 
/// Whether to display subtitles.
///
/// By default, this is set to `false`, which hides them.
```

2023-07-03 03:53 UTC, PranavMasekar commented
@diegotori I have done the changes

2023-07-24 18:29 UTC, diegotori requested changes

2024-08-19 05:39 UTC, nateshmbhat commented
any updates on this ?

2026-08-27 09:41 UTC, Ortes commented
@diegotori this one looks safe to close — the feature landed independently.

`master` already has `ChewieController.showSubtitles` (default `false`), added in #648 and renamed from `showSubtitlesPerDefault` in `77798a5`. All three skins gate on it the same way this PR proposes:
`_subtitleOn = chewieController.showSubtitles && (chewieController.subtitle?.isNotEmpty ?? false)` in `material_controls.dart`, `material_desktop_controls.dart` and `cupertino_controls.dart`.

That's a superset of this PR — same flag, same default, same three skins, plus a runtime toggle button this PR doesn't have. I couldn't find anything here that's still missing upstream, and the branch is now conflicting.

Thanks @PranavMasekar for the original proposal — it effectively shipped.

2026-08-27 12:08 UTC, closed without merging