Fixed pop the wrong page when changing the speed
fluttercommunity/chewie pull request #871
Opened 2024-11-19 20:36 UTC by akmalova

**Fixed pop the wrong page when changing the speed**
Issue: https://github.com/fluttercommunity/chewie/issues/618

This was during the speed change and the use of additional options. This was due to the use of the wrong context. In order for the bottom sheet to close correctly, we need to use the context of the bottom sheet itself.
`
await showModalBottomSheet<OptionItem>(
              context: context,
              isScrollControlled: true,
              useRootNavigator: chewieController.useRootNavigator,
              builder: (context) => OptionsDialog(
                options: options,
                options: _buildOptions(context),
                cancelButtonText:
                    chewieController.optionsTranslation?.cancelButtonText,
              ),
`

In this regard, I had to add the `BuildContext context` parameter to the `OptionItem` model in `onTap` callback. Now there is no such problem.
`Function(BuildContext context)? onTap;`

Such a bug was noticed in a project where we use AutoRoute package, so maybe this bug has something to do with using this package.

2025-01-06 17:39 UTC, diegotori requested changes
Other than this nit, everything else looks good for this PR.

2025-01-09 16:42 UTC, akmalova commented
Done

2025-01-09 17:40 UTC, diegotori requested changes

2025-01-09 17:40 UTC, diegotori commented on lib/src/cupertino/widgets/cupertino_options_dialog.dart
> +                onPressed: () => option.onTap!(context),
Please modify `OptionItem.onTap` so that it's not null:

```dart
onPressed: () => option.onTap(context),
```

2025-01-09 17:40 UTC, diegotori commented on lib/src/models/option_item.dart
> +  Function(BuildContext context)? onTap;
Two things:

1. Make all of this class's properties `final`.
2. Rename this function to:

```dart
final void Function(BuildContext context) onTap;
```

2025-01-09 17:40 UTC, diegotori commented on lib/src/material/widgets/options_dialog.dart
> +                onTap: () => widget.options[i].onTap?.call(context),
If you make `OptionItem.onTap` non-null, then you won't need to do this.

2025-01-09 17:41 UTC, diegotori commented
@akmalova Please run `dart format` on the current changes. Also added some additional feedback. Please address that in order for me to approve your changes. Thanks.

2025-01-09 17:41 UTC, diegotori commented
Lastly, please re-sync your changes with `master`. Thanks.

2025-01-13 21:27 UTC, diegotori commented
@akmalova you still with us on this PR?

2025-01-16 16:25 UTC, akmalova commented
@diegotori Yes, I'm sorry, I didn't have time. I've fixed everything now.

2025-01-16 17:06 UTC, diegotori approved these changes
LGTM.

2025-01-16 17:06 UTC, merged